### ISSUE TITLE
Unable to run debug enclave on guest

### ISSUE THREAD

**Issue by zeyu-zh** [intel/kvm-sgx#17] opened 2020-06-23 18:46 UTC
Hello,

I got problems when trying to run debug enclave on the guest:
1. When I run SampleEnclave in HW debug mode, it returns unexpected_error. Then I hook the EINIT of SGX driver, I find it returns 16 (SGX_INVALID_EINIT_TOKEN).
2. However, the platform enclave of AESMD can run successfully. I thought this is because Intel's enclaves don't have a valid token, so the CPU will only check MRSINGER, instead of a token.
3. I inspect the code of kvm-sgx, it seems that the KVM will intercept and execute the guest's EINIT. So I remove the code of intercepting EINIT (bitmap), and then the debug enclave can run on the guest successfully!

Any ideas? Does this mean that tokens cannot cross virtual machines?

My setup:
1. Host
Dell XPS 15, Core i9-8950HK
SGX1 and SGX_LC, 128MB EPC
IA32_SGXPUBKEYHASH is writable
kvm-sgx v5.6, SGX PSW v2.9

2. Guest
ubuntu 18.04, kernel 5.3.0-53.generic
linux-sgx-driver (sgx2) and linux-sgx (v2.9)
SGX1 and SGX_LC 32MB EPC

Thanks!

**Comment by sean-jc** [comment] 2020-07-01 21:06
Well this is embarrassing.  The code to translate the GPA->HVA of the various incoming structures forgot the "minor" detail of propagating the page offset, e.g. given a token at 0xbeef0800, KVM would unintentionally drop the 0x800 offset and pass in 0xbeef0000 for the address of the token.  This only broke tokens because all other addresses that are passed to EINIT and ECREATE are page aligned, or in the case of pageinfo are explicitly copied to kernel memory via a different path.

Because the Linux guest SGX driver uses a single kernel page for sigstruct+token, i.e. sigstruct=0xbeef0000, token=0xbeef0800, the end result is the the host would end up interpreting the sigstruct as a token.  The corresponding field for token.valid in sigstruct is the header type, which must be hardcoded to 0x6, which meant that the token was always invalid.

This escaped my testing because I stopped running non-LC kernels a while back, i.e. didn't test with anything that relied on tokens.  That's now resurrected and remedied :-)

Thanks for the report!  Should have a new version pushed today.

**Comment by sean-jc** [comment] 2020-07-02 05:02
Fixed in sgx-v5.6.0-rc5-r2.  Holler if it's still broken in your environment, I tested via my own token-based tool and not the SDK.  I gave up trying to get the SDK functional after an hour of pain.

**Closed as completed by sean-jc** 2020-07-02 05:02 UTC

**Comment by johnvenn** [comment] 2020-07-02 08:03
> Well this is embarrassing. The code to translate the GPA->HVA of the various incoming structures forgot the "minor" detail of propagating the page offset, e.g. given a token at 0xbeef0800, KVM would unintentionally drop the 0x800 offset and pass in 0xbeef0000 for the address of the token. This only broke tokens because all other addresses that are passed to EINIT and ECREATE are page aligned, or in the case of pageinfo are explicitly copied to kernel memory via a different path.
> 
> Because the Linux guest SGX driver uses a single kernel page for sigstruct+token, i.e. sigstruct=0xbeef0000, token=0xbeef0800, the end result is the the host would end up interpreting the sigstruct as a token. The corresponding field for token.valid in sigstruct is the header type, which must be hardcoded to 0x6, which meant that the token was always invalid.
> 
> This escaped my testing because I stopped running non-LC kernels a while back, i.e. didn't test with anything that relied on tokens. That's now resurrected and remedied :-)
> 
> Thanks for the report! Should have a new version pushed today.

@sean-jc , this is Xiangping from SGX team. Just wonder what is non-LC kernels, and how to reproduce the issue, 'cause we are now using sgx-v5.6.0-rc5-r1 for test. We are considering adding the test case in future test and support you with the environment to reproduce bugs.
