### ISSUE TITLE
unable to run sample enclave on guest

### ISSUE THREAD

**Issue by tyxeron** [intel/kvm-sgx#5] opened 2018-06-24 17:14 UTC
I ran into problems when trying to install SGX PSW/SDK on the guest.
* There is no /dev/mei0 so installing PSW fails, when also installing the iclsclient
* When trying to install the PSW without installing the iclsclient (I read that this is/should be possible)
   the aesmd service runs without showing an error but if I try to run sample code in HW mode, I get sgx_status = 0x4001, SGX_ERROR_SERVICE_UNAVAILABLE.
   When I looked at the system logs, It says that "systed could not stat /dev/sgx"

My setup:
	Host does not have SGX driver/SDK/PSW installed.
	I run the VM with following command:
`qemu-system-x86_64 --enable-kvm --machine epc=0x4000 -cpu host -drive file=/home/joel/.local/share/libvirt/images/debian9.qcow2 -m 4G -smp 4 -vga qxl`
The guest OS is debian stretch.

**Comment by sean-jc** [comment] 2018-06-25 22:56
Does the guest kernel have an SGX driver installed and running?  KVM only exposes SGX and EPC to the guest, the guest still needs its own SGX support.

**Comment by tyxeron** [comment] 2018-06-26 08:15
Yes, sgx driver is installed and 'isgx' is listed in lsmod. dmesg shows following related to sgx:

 isgx: loading out-of-tree module taints kernel
 intel_sgx: Intel SGX Driver v0.11
 intel_sgx: INT0E=C:00: EPC bank 0xc0000000-0xc0004000
 intel_sgx: second initialization call skipped

Kernel is 4.9.0-6-amd64.

Any ideas? I will try it with a different kernel and see if that changes anything.

**Comment by sean-jc** [comment] 2018-06-26 12:46
What versions of the driver and SDK are you using?  Have you tried moving to a newer, or perhaps older, version of the SGX/SDK?  

The `systed could not stat /dev/sgx` warning in the log is odd.  The out-of-tree driver creates the SGX IOCTL device as `/dev/isgx`, not `/dev/sgx`.  I know older versions of the SDK/PSW looked for `/dev/isgx`, while newer versions appear to support both, e.g. query `/dev/isgx` first and then `/dev/sgx` if the former is not found.

**Comment by tyxeron** [comment] 2018-06-26 13:51
the driver is the 2.1 release and SDK was not a release, but build directly from the newest commit (about 5 days ago), maybe that is the problem. I am currently trying out Ubuntu 16.04.4 as Guest OS, SGX SDK is 2.1.3 and driver is again 2.1. I will report back when I am done installing.

**Comment by tyxeron** [comment] 2018-06-26 15:04
I tried, but also failed with the same result. No /dev/mei0 and Sample Code Enclaves fail with 0x4001.
There is a new Log entry
 `isgx: module verification failed:signature and/or required key missing - tainting kernel`
I read that this is just a warning, not an error.

I attach the configuration of the Host kernel obtained by 
`/boot/config-$(uname -r)` just in case.

[config.txt](https://github.com/intel/kvm-sgx/files/2137648/config.txt)

**Comment by tyxeron** [comment] 2018-07-01 14:48
Any ideas on that?

**Comment by sean-jc** [comment] 2018-07-02 17:05
For the `/dev/mei0` issue, I recommend submitting an [SDK issue ](https://github.com/intel/linux-sgx/issues) explicitly inquiring about ME/PSW support in VMs.  IIRC exposing the ME to VMs isn't be supported on current hardware, but my ME/PSE knowledge is fairly limited so I could just be making things up.

As for `/dev/sgx` not being available, can you see `/dev/sgx` or `/dev/isgx` when manually looking at `/dev`?  If so, it might be a permission issue, e.g. older versions of the driver created `/dev/sgx` with unrestricted permissions, but newer versions limit `/dev/sgx` to root by default, e.g. 0660.  If `/dev/sgx` is available and the permissions are correct I would try reproducing the issue on bare metal.

One other experiment would be to increase the virtual EPC size to a more reasonable value, e.g. 4mb or more.

**Comment by tyxeron** [comment] 2018-07-04 13:52
I did increase the EPC size to 4mb and it solved the issues regarding the SGX Error 0x4001.
I am able to run all but RemoteAttestation and SealedData.

RemoteAttestation fails with `error while loading shared libraries: libsample_libcrypto.so: cannot open shared object file: No such file or directory`

Sealed data fails with: `cannot get platform service capability, error code = 0x1`

But I assume these stem from the missing PSW support in VM's

Thank you very much for your help. I will later submit an SDK issue as you mentioned.

**Comment by sean-jc** [comment] 2018-07-05 15:02
Glad you got it working, closing this issue.

**Closed as completed by sean-jc** 2018-07-05 15:02 UTC

**Comment by maincui** [comment] 2019-09-01 10:33
@tyxeron , have you filed the issue, NO MEI in (Azure) VM for PSW? I am running into the same problem and blocked since it's still not easy to find a hardware support SGX in 2019, sad.

Besides, it's so weird README.md of this project contains no step by step guide to build it. Is it identical to linux-sgx?

**Comment by sean-jc** [comment] 2019-09-03 14:27
This repository provides patches for adding SGX support to KVM, i.e. a host Linux kernel.  Building and installing a Linux kernel is dependent on your environment, and said build process is unaffected by these patches, hence the disclaimer:

> This readme assumes that the reader is familiar with Intel® SGX, KVM and Linux, and has experience building the Linux kernel.

**Comment by maincui** [comment] 2019-09-04 03:36
Sorry for my intrusive problem. seems linux-sgx is my target and a bare metal machine with SGX support is what I need now.
